### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by Asuna3244** [Infinituum17/LabellingContainers#21]
[Uploading latest.log…]()

Can you fix this? Or tell me what I have to do?

**Comment by Asuna3244** [comment]
I can't upload anything

**Comment by Asuna3244** [comment]
I'll send you a link to the log

https://paste.modularity.gg/paste/?content=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F768367574001778729%2F1211017579183874048%2Flatest.log&raw=false

**Comment by Infinituum17** [comment]
Yeah yeah, I'll fix it as soon as possible, my mistake. I'll close this issue when it's fixed, thank you for the report

**Comment by Infinituum17** [comment]
Ok now it's fixed, you can try to play with version `1.4.5` and it should work fine.

Thank you again for your bug report.

**Comment by Asuna3244** [comment]
no problem
