### ISSUE TITLE
Tweakermore & LabellingContainer crash at launch

### ISSUE THREAD

**Issue by dadoirie** [Infinituum17/LabellingContainers#4]
Any chance those 2 mods could run together?
https://mclo.gs/4FhYVgA

[TweakerMore](https://www.curseforge.com/minecraft/mc-mods/tweakermore) is a client side only mod and does crash minecraft during launch.
Would it be possible making LabellingContainers compatible with it or is this a unavoidable conflict?

**Comment by Infinituum17** [comment]
Expect a new version soon 😉

**Comment by Infinituum17** [comment]
A new version is out now! Should work with TweakerMore. If you notice any other bugs with the mod feel free to open other issues here and thank you for reporting that bug
