### ISSUE TITLE
[BUG] Farmer's Delight cherry and bamboo cabinets not compatible

### ISSUE THREAD

**Issue by YLlywelyn** [Infinituum17/LabellingContainers#48]
**Minecraft Version**
1.20.1

**Mod Version**
1.6.1

**Describe the bug**
Issue#46 states that Farmer's Delight cabinets have been added to the list of compatible blocks, however when I try to label cherry or bamboo containers I get the message "You can't tag this block!".

**Comment by Infinituum17** [comment]
Hi, thank you for your report. I'll look into it asap

**Comment by Infinituum17** [comment]
Update: I'm stupid and I forgot to add these two blocks to the config, I'll release an update soon that resolves this issue.

BUT also you don't have to wait for the update, you can do it yourself if you run these two commands with admin permissions in any world:
- `/labelconfig add-item farmersdelight:bamboo_cabinet`
- `/labelconfig add-item farmersdelight:cherry_cabinet`

I hope this resolves your issue!
