### ISSUE TITLE
[BUG] /tellraw broken (and /tell)

### ISSUE THREAD

**Issue by PalgamingHD** [Infinituum17/LabellingContainers#49]
**Minecraft Version**
1.20.1

**Mod Version**
1.6.2

**Describe the bug**
Using /tellraw fails to work and throws an error

**Crash Report or Log**
On single player: 
03:06:15.486
net.minecraft.class_338
Render thread
[System] [CHAT] An unexpected error occurred trying to execute that command

On my server (a few other mods installed):
https://pastebin.com/MSkAQk5Q

**Comment by Infinituum17** [comment]
Hi thank you for your big report. I'll look into it as soon as I can.
