### ISSUE TITLE
[BUG] Broken Texture

### ISSUE THREAD

**Issue by Bleeks360** [Infinituum17/LabellingContainers#50]
**Minecraft Version**
1.20.4 w/ Fabric Loader

**Mod Version**
1.6.3

**Describe the bug**
It seems there is a broken texture with the Label Printer item as I am getting the dreaded purple and black squares. When I removed and reinstalled the mod the issue was not fixed, however when I installed the previous verion 1.6.1 the texture was correct.

**Comment by Infinituum17** [comment]
Thank you for your bug report! I just released a new version for mc1.20.4 (1.6.4) and it should be fixed

**Comment by Infinituum17** [comment]
Small update: it actually isn't fixed ahaha I'll look into it 'cause it's a bigger problem than I expected

**Comment by Infinituum17** [comment]
Ok, now i'm 100% sure that it works, thank you again
