### ISSUE TITLE
Reinforced Chests（Reinforced Chests）

### ISSUE THREAD

**Issue by whydm2003724** [Infinituum17/LabellingContainers#53]
**What mod would you want to be compatible with Labelling Containers?**
Ex. Labelling Containers

**List of blocks that you'd like to add**
Ex. Chests, Shulker Boxes, ...

**CurseForge link**
[Ex. https://www.curseforge.com/minecraft/mc-mods/labelling-containers](https://www.curseforge.com/minecraft/mc-mods/reinforced-chests)

Thank you for creating an excellent module, it's great

**Comment by Infinituum17** [comment]
Hi, have you got a list of blocks that you want to add specifically?

**Comment by Infinituum17** [comment]
It's working fine in MC 1.20.1, I just tested it.

If it's also the version you're using, you should take a look at the mod's commands, mainly because Reinforced Chests blocks aren't added by default, so you have to add them manually.

**Comment by whydm2003724** [comment]
> 您好，您使用的是哪个MC版本？
Hello, I apologize for the delayed response as I did not check the website in a timely manner. I am using version 1.20.1

**Comment by whydm2003724** [comment]
> Hi, what MC version are you using?

Hello, I apologize for the delayed response as I did not check the website in a timely manner. I am using version 1.20.1

**Comment by whydm2003724** [comment]
> It's working fine in MC 1.20.1, I just tested it.
> 
> If it's also the version you're using, you should take a look at the mod's commands, mainly because Reinforced Chests blocks aren't added by default, so you have to add them manually.

Okay, I'll give it a try. Thank you for your reminder and assistance
