### ISSUE TITLE
Could we get a forge version?

### ISSUE THREAD

**Issue by SeanChengN** [Infinituum17/LabellingContainers#6]
I guess this is the best label mod out there, do you have any plans for a forge version?

**Comment by Infinituum17** [comment]
If I can figure out how Architectury works I'll make a Forge version of the mod. Maybe I'll see how to work with it in the next few days.

**Comment by Infinituum17** [comment]
The mod now runs on Forge too! (finally)

The Forge version is now available for 1.20.1 - 1.20.2 - 1.20.3 - 1.20.4

In the next few days I'll backport code to include 1.19.2 / 1.20

**Comment by SeanChengN** [comment]
Thanks a lot!!!
