### ISSUE TITLE
Missing texture [BUG]

### ISSUE THREAD

**Issue by hoffmannE** [Infinituum17/LabellingContainers#64]
**Minecraft Version**
1.21

**Mod loader** 
Fabric 0.16.5

**Mod Version**
1.9.1

**Describe the bug**
Missing texture bug in GUI, item. Also have a strange description of item. 

**Screenshots**
![2024-09-27_20 29 57](https://github.com/user-attachments/assets/3a8bf310-9f0c-454f-9eae-2c6fa3e05ecf)
![2024-09-27_20 30 01](https://github.com/user-attachments/assets/3b087c4b-8ce6-4532-94d5-de9c49e4d6ab)
![2024-09-27_20 29 41](https://github.com/user-attachments/assets/c00ac42e-5122-488c-8bfb-b6d55cead8a4)

**Comment by hoffmannE** [comment]
I would also like to add to my previous post, I checked it not in my modpack, in the clean version of fabric this bug also appears.

**Comment by Infinituum17** [comment]
Thank you for your report! I'll check asap to fix it

**Comment by Infinituum17** [comment]
> I would also like to add to my previous post, I checked it not in my modpack, in the clean version of fabric this bug also appears.

The bug is now fixed in version 1.9.2, thank you for reporting it and playing with my mod

**Comment by hoffmannE** [comment]
Your mod is really cool. Thank you for fix
